### ISSUE TITLE
Leaked connection

### ISSUE THREAD

**Issue by fnobilia** [RADAR-CNS/RADAR-RedcapIntegration#2]
Log reports 
`WARNING [OkHttp ConnectionPool] okhttp3.internal.platform.Platform.log A connection to http://34.250.170.242:9000/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);`

The `org.radarcns.oauth` does not close some response body

**Comment by blootsvoets** [comment]
Btw, related, a proper way to handle okhttp Response objects is in a try-with-resources block. This prevents any memory leaks.

```java
try (Response response = call.execute()) {
    // do something
}
```
