### ISSUE TITLE
Better Logging if work-package for a project in MP is null

### ISSUE THREAD

**Issue by yatharthranjan** [RADAR-CNS/RADAR-RedcapIntegration#7]
Right now the integration app just Logs that the `Subject cannot be created` if the work-package for the Project in Management Portal is `null` and throws a `NullPointerException`.

> Caused by: java.lang.NullPointerException: null
        at org.radarcns.redcap.managementportal.MpClient.validateProject(MpClient.java:165)
        at org.radarcns.redcap.managementportal.MpClient.getProject(MpClient.java:140)
        at org.radarcns.redcap.managementportal.MpClient.<init>(MpClient.java:86)

This is because the work-package is required for generating the human-readable-identifier. The Logs are confusing right now and should be improved to provide the correct reason for the `NullPointerException`.

**Comment by afolarin** [comment]
Would be good if the Management Portal perhaps made those fields mandatory.

**Comment by yatharthranjan** [comment]
Yes that would be better. Maybe @nivemaham and @dennyverbeeck can have a look and provide suggestions.

**Comment by nivemaham** [comment]
@yatharthranjan If we want to keep MP general without depending on redcap, we cannot have these constraints implemented on MP side. This has been already discussed during the implementation of Redcap-integration. I would suggest to have these implemented on redcap-integration side.

**Comment by yatharthranjan** [comment]
Okay then, i think we will update the integration app. What do you think @afolarin ?

**Comment by afolarin** [comment]
OK perhaps Radar Integration can verify this Work-Package is not null, and log something sensible.

**Comment by yatharthranjan** [comment]
Closed with PR #10
